name: Build & Code Quality Checks

on:
  pull_request:
    branches: ['develop', 'main']
    types: ['opened', 'reopened', 'synchronize']

env:
  NODE_OPTIONS: "--no-warnings"

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      - name: Execute quality checks
        run: |
          npm run check:circular
          npm run check:duplicates

      - name: Execute security checks
        run: |
          npm run check:security

      - name: Execute build checks
        run: |
          npm run build
